openapi: 3.0.3
info:
  title: L3 Miage BDD Project
  description: |
    Manage Photo Library
  version: 1.0.0
servers:
  - url: "http://localhost:8080"
paths:
  /api/v1/impressions:
    get:
      summary: Get all impressions
      operationId: find-impressions
      responses:
        200:
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Impression"